server:
  port: 5002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salon_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
management:
    endpoints:
        web:
            exposure:
                include: "*"